/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ddukddak;


public class App {
    public static void main(String[] args) {
        try {
            Simulator simulator = new Simulator(178, 200, 1000000);
            System.out.println(simulator.run());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
